// css_topic_map.js
// Maps each CSS property name to a lesson topic category.
// Used by css_guide_engine.js to group atoz_properties_lessons by topic.

const css_topic_map = {

  // ── ACCESSIBILITY & UI CONTROLS ──────────────────────────────────────────
  "accent-color":           "Accessibility & UI Controls",
  "caret-color":            "Accessibility & UI Controls",
  "pointer-events":         "Accessibility & UI Controls",
  "user-select":            "Accessibility & UI Controls",
  "cursor":                 "Accessibility & UI Controls",
  "resize":                 "Accessibility & UI Controls",

  // ── ANIMATION ────────────────────────────────────────────────────────────
  "animation":                    "Animation",
  "animation-delay":              "Animation",
  "animation-direction":          "Animation",
  "animation-duration":           "Animation",
  "animation-fill-mode":          "Animation",
  "animation-iteration-count":    "Animation",
  "animation-name":               "Animation",
  "animation-play-state":         "Animation",
  "animation-timing-function":    "Animation",

  // ── BACKGROUNDS ──────────────────────────────────────────────────────────
  "background":               "Backgrounds",
  "background-attachment":    "Backgrounds",
  "background-blend-mode":    "Backgrounds",
  "background-clip":          "Backgrounds",
  "background-color":         "Backgrounds",
  "background-image":         "Backgrounds",
  "background-origin":        "Backgrounds",
  "background-position":      "Backgrounds",
  "background-position-x":    "Backgrounds",
  "background-position-y":    "Backgrounds",
  "background-repeat":        "Backgrounds",
  "background-size":          "Backgrounds",

  // ── BORDERS ──────────────────────────────────────────────────────────────
  "border":                         "Borders",
  "border-bottom":                  "Borders",
  "border-bottom-color":            "Borders",
  "border-bottom-left-radius":      "Borders",
  "border-bottom-right-radius":     "Borders",
  "border-bottom-style":            "Borders",
  "border-bottom-width":            "Borders",
  "border-collapse":                "Borders",
  "border-color":                   "Borders",
  "border-image":                   "Borders",
  "border-image-outset":            "Borders",
  "border-image-repeat":            "Borders",
  "border-image-slice":             "Borders",
  "border-image-source":            "Borders",
  "border-image-width":             "Borders",
  "border-left":                    "Borders",
  "border-left-color":              "Borders",
  "border-left-style":              "Borders",
  "border-left-width":              "Borders",
  "border-radius":                  "Borders",
  "border-right":                   "Borders",
  "border-right-color":             "Borders",
  "border-right-style":             "Borders",
  "border-right-width":             "Borders",
  "border-spacing":                 "Borders",
  "border-style":                   "Borders",
  "border-top":                     "Borders",
  "border-top-color":               "Borders",
  "border-top-left-radius":         "Borders",
  "border-top-right-radius":        "Borders",
  "border-top-style":               "Borders",
  "border-top-width":               "Borders",
  "border-width":                   "Borders",
  "box-decoration-break":           "Borders",
  "box-reflect":                    "Borders",
  "box-shadow":                     "Borders",

  // ── LOGICAL BORDERS (inline/block) ───────────────────────────────────────
  "border-block":                   "Logical Properties",
  "border-block-color":             "Logical Properties",
  "border-block-end":               "Logical Properties",
  "border-block-end-color":         "Logical Properties",
  "border-block-end-style":         "Logical Properties",
  "border-block-end-width":         "Logical Properties",
  "border-block-start":             "Logical Properties",
  "border-block-start-color":       "Logical Properties",
  "border-block-start-style":       "Logical Properties",
  "border-block-start-width":       "Logical Properties",
  "border-block-style":             "Logical Properties",
  "border-block-width":             "Logical Properties",
  "border-inline":                  "Logical Properties",
  "border-inline-color":            "Logical Properties",
  "border-inline-end":              "Logical Properties",
  "border-inline-end-color":        "Logical Properties",
  "border-inline-end-style":        "Logical Properties",
  "border-inline-end-width":        "Logical Properties",
  "border-inline-start":            "Logical Properties",
  "border-inline-start-color":      "Logical Properties",
  "border-inline-start-style":      "Logical Properties",
  "border-inline-start-width":      "Logical Properties",
  "border-inline-style":            "Logical Properties",
  "border-inline-width":            "Logical Properties",
  "border-end-end-radius":          "Logical Properties",
  "border-end-start-radius":        "Logical Properties",
  "border-start-end-radius":        "Logical Properties",
  "border-start-start-radius":      "Logical Properties",
  "block-size":                     "Logical Properties",
  "inline-size":                    "Logical Properties",
  "max-block-size":                 "Logical Properties",
  "max-inline-size":                "Logical Properties",
  "min-block-size":                 "Logical Properties",
  "min-inline-size":                "Logical Properties",
  "inset":                          "Logical Properties",
  "inset-block":                    "Logical Properties",
  "inset-block-end":                "Logical Properties",
  "inset-block-start":              "Logical Properties",
  "inset-inline":                   "Logical Properties",
  "inset-inline-end":               "Logical Properties",
  "inset-inline-start":             "Logical Properties",
  "margin-block":                   "Logical Properties",
  "margin-block-end":               "Logical Properties",
  "margin-block-start":             "Logical Properties",
  "margin-inline":                  "Logical Properties",
  "margin-inline-end":              "Logical Properties",
  "margin-inline-start":            "Logical Properties",
  "padding-block":                  "Logical Properties",
  "padding-block-end":              "Logical Properties",
  "padding-block-start":            "Logical Properties",
  "padding-inline":                 "Logical Properties",
  "padding-inline-end":             "Logical Properties",
  "padding-inline-start":           "Logical Properties",

  // ── BOX MODEL ────────────────────────────────────────────────────────────
  "box-sizing":       "Box Model",
  "height":           "Box Model",
  "width":            "Box Model",
  "max-height":       "Box Model",
  "max-width":        "Box Model",
  "min-height":       "Box Model",
  "min-width":        "Box Model",
  "margin":           "Box Model",
  "margin-bottom":    "Box Model",
  "margin-left":      "Box Model",
  "margin-right":     "Box Model",
  "margin-top":       "Box Model",
  "padding":          "Box Model",
  "padding-bottom":   "Box Model",
  "padding-left":     "Box Model",
  "padding-right":    "Box Model",
  "padding-top":      "Box Model",
  "aspect-ratio":     "Box Model",
  "overflow":         "Box Model",
  "overflow-anchor":  "Box Model",
  "overflow-wrap":    "Box Model",
  "overflow-x":       "Box Model",
  "overflow-y":       "Box Model",

  // ── COLOR ────────────────────────────────────────────────────────────────
  "color":          "Color",
  "color-scheme":   "Color",
  "opacity":        "Color",
  "mix-blend-mode": "Color",
  "isolation":      "Color",

  // ── COLUMNS (Multi-column layout) ─────────────────────────────────────────
  "column-count":       "Multi-Column Layout",
  "column-fill":        "Multi-Column Layout",
  "column-gap":         "Multi-Column Layout",
  "column-rule":        "Multi-Column Layout",
  "column-rule-color":  "Multi-Column Layout",
  "column-rule-style":  "Multi-Column Layout",
  "column-rule-width":  "Multi-Column Layout",
  "column-span":        "Multi-Column Layout",
  "column-width":       "Multi-Column Layout",
  "columns":            "Multi-Column Layout",
  "break-after":        "Multi-Column Layout",
  "break-before":       "Multi-Column Layout",
  "break-inside":       "Multi-Column Layout",
  "orphans":            "Multi-Column Layout",
  "widows":             "Multi-Column Layout",

  // ── CONTENT & COUNTERS ───────────────────────────────────────────────────
  "content":            "Content & Counters",
  "counter-increment":  "Content & Counters",
  "counter-reset":      "Content & Counters",
  "counter-set":        "Content & Counters",
  "quotes":             "Content & Counters",

  // ── DISPLAY & VISIBILITY ─────────────────────────────────────────────────
  "display":      "Display & Visibility",
  "visibility":   "Display & Visibility",
  "all":          "Display & Visibility",

  // ── EFFECTS & FILTERS ────────────────────────────────────────────────────
  "backdrop-filter":    "Effects & Filters",
  "filter":             "Effects & Filters",
  "image-rendering":    "Effects & Filters",
  "paint-order":        "Effects & Filters",

  // ── FLEXBOX ──────────────────────────────────────────────────────────────
  "flex":           "Flexbox",
  "flex-basis":     "Flexbox",
  "flex-direction": "Flexbox",
  "flex-flow":      "Flexbox",
  "flex-grow":      "Flexbox",
  "flex-shrink":    "Flexbox",
  "flex-wrap":      "Flexbox",
  "align-content":  "Flexbox",
  "align-items":    "Flexbox",
  "align-self":     "Flexbox",
  "justify-content":"Flexbox",
  "justify-items":  "Flexbox",
  "justify-self":   "Flexbox",
  "place-content":  "Flexbox",
  "place-items":    "Flexbox",
  "place-self":     "Flexbox",
  "gap":            "Flexbox",
  "row-gap":        "Flexbox",
  "order":          "Flexbox",

  // ── FLOAT & CLEAR ────────────────────────────────────────────────────────
  "float":          "Float & Clear",
  "clear":          "Float & Clear",
  "shape-outside":  "Float & Clear",

  // ── FONTS & TYPOGRAPHY ───────────────────────────────────────────────────
  "font":                   "Fonts & Typography",
  "font-family":            "Fonts & Typography",
  "font-feature-settings":  "Fonts & Typography",
  "font-kerning":           "Fonts & Typography",
  "font-size":              "Fonts & Typography",
  "font-size-adjust":       "Fonts & Typography",
  "font-stretch":           "Fonts & Typography",
  "font-style":             "Fonts & Typography",
  "font-variant":           "Fonts & Typography",
  "font-variant-caps":      "Fonts & Typography",
  "font-weight":            "Fonts & Typography",
  "initial-letter":         "Fonts & Typography",

  // ── GRID ─────────────────────────────────────────────────────────────────
  "grid":                   "Grid Layout",
  "grid-area":              "Grid Layout",
  "grid-auto-columns":      "Grid Layout",
  "grid-auto-flow":         "Grid Layout",
  "grid-auto-rows":         "Grid Layout",
  "grid-column":            "Grid Layout",
  "grid-column-end":        "Grid Layout",
  "grid-column-start":      "Grid Layout",
  "grid-row":               "Grid Layout",
  "grid-row-end":           "Grid Layout",
  "grid-row-start":         "Grid Layout",
  "grid-template":          "Grid Layout",
  "grid-template-areas":    "Grid Layout",
  "grid-template-columns":  "Grid Layout",
  "grid-template-rows":     "Grid Layout",

  // ── IMAGES & OBJECTS ─────────────────────────────────────────────────────
  "object-fit":       "Images & Objects",
  "object-position":  "Images & Objects",

  // ── LISTS ────────────────────────────────────────────────────────────────
  "list-style":           "Lists",
  "list-style-image":     "Lists",
  "list-style-position":  "Lists",
  "list-style-type":      "Lists",

  // ── MASK ─────────────────────────────────────────────────────────────────
  "mask":             "Masking",
  "mask-clip":        "Masking",
  "mask-composite":   "Masking",
  "mask-image":       "Masking",
  "mask-mode":        "Masking",
  "mask-origin":      "Masking",
  "mask-position":    "Masking",
  "mask-repeat":      "Masking",
  "mask-size":        "Masking",
  "mask-type":        "Masking",

  // ── OUTLINE ──────────────────────────────────────────────────────────────
  "outline":          "Outline",
  "outline-color":    "Outline",
  "outline-offset":   "Outline",
  "outline-style":    "Outline",
  "outline-width":    "Outline",

  // ── POSITIONING ──────────────────────────────────────────────────────────
  "position":   "Positioning",
  "top":        "Positioning",
  "right":      "Positioning",
  "bottom":     "Positioning",  
  "left":       "Positioning",
  "z-index":    "Positioning",
  "float":      "Positioning",
  "clear":      "Positioning",

  // ── PERSPECTIVE & 3D ─────────────────────────────────────────────────────
  "backface-visibility":  "3D & Perspective",
  "perspective":          "3D & Perspective",
  "perspective-origin":   "3D & Perspective",

  // ── SCROLL ───────────────────────────────────────────────────────────────
  "scroll-behavior":          "Scroll & Snap",
  "scroll-margin":            "Scroll & Snap",
  "scroll-margin-top":        "Scroll & Snap",
  "scroll-padding":           "Scroll & Snap",
  "scroll-snap-align":        "Scroll & Snap",
  "scroll-snap-stop":         "Scroll & Snap",
  "scroll-snap-type":         "Scroll & Snap",
  "scrollbar-color":          "Scroll & Snap",
  "overscroll-behavior":      "Scroll & Snap",
  "overscroll-behavior-block":"Scroll & Snap",
  "overscroll-behavior-inline":"Scroll & Snap",
  "overscroll-behavior-x":    "Scroll & Snap",
  "overscroll-behavior-y":    "Scroll & Snap",

  // ── TABLES ───────────────────────────────────────────────────────────────
  "border-collapse":  "Tables",
  "border-spacing":   "Tables",
  "caption-side":     "Tables",
  "empty-cells":      "Tables",
  "table-layout":     "Tables",
  "vertical-align":   "Tables",

  // ── TEXT ─────────────────────────────────────────────────────────────────
  "color":                    "Text",
  "direction":                "Text",
  "hanging-punctuation":      "Text",
  "hyphens":                  "Text",
  "hyphenate-character":      "Text",
  "letter-spacing":           "Text",
  "line-height":              "Text",
  "tab-size":                 "Text",
  "text-align":               "Text",
  "text-align-last":          "Text",
  "text-decoration":          "Text",
  "text-decoration-color":    "Text",
  "text-decoration-line":     "Text",
  "text-decoration-style":    "Text",
  "text-decoration-thickness":"Text",
  "text-emphasis":            "Text",
  "text-indent":              "Text",
  "text-justify":             "Text",
  "text-orientation":         "Text",
  "text-overflow":            "Text",
  "text-shadow":              "Text",
  "text-transform":           "Text",
  "text-underline-offset":    "Text",
  "text-underline-position":  "Text",
  "unicode-bidi":             "Text",
  "white-space":              "Text",
  "word-break":               "Text",
  "word-spacing":             "Text",
  "word-wrap":                "Text",
  "writing-mode":             "Text",

  // ── TRANSFORMS ───────────────────────────────────────────────────────────
  "rotate":             "Transforms",
  "scale":              "Transforms",
  "translate":          "Transforms",
  "transform":          "Transforms",
  "transform-origin":   "Transforms",
  "transform-style":    "Transforms",

  // ── TRANSITIONS ──────────────────────────────────────────────────────────
  "transition":                   "Transitions",
  "transition-delay":             "Transitions",
  "transition-duration":          "Transitions",
  "transition-property":          "Transitions",
  "transition-timing-function":   "Transitions",

  // ── CLIPPING & SHAPE ─────────────────────────────────────────────────────
  "clip":       "Clipping & Shape",
  "clip-path":  "Clipping & Shape",

  // ── MISCELLANEOUS ────────────────────────────────────────────────────────
  "appearance":         "Miscellaneous"

};
